### ISSUE TITLE
Mostrar el año en el título de inscripciones

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/encuesta-docente#19]
En el título de la pantalla mostrar el año de las inscripciones que se está filtrando
![image](https://user-images.githubusercontent.com/831628/63466666-1e7a7580-c43a-11e9-8c5c-0aff49725f14.png)

En esa pantalla debería mostrar **Inscripciones 2019**

**Comment by sergioviera** [comment]
Muestra el título pero no lo actualiza si aplico un filtro (por ejemplo: año académico 2018).
Los datos si los actualiza, pero no el título.
![image](https://user-images.githubusercontent.com/831628/64213029-d3bd1c80-ce81-11e9-9e80-1cb76f7987c5.png)

**Comment by nulmete** [comment]
Cuando se apreta cualquiera de los botones "Ver" (que filtra el campo que se encuentra a la izquierda:

![image](https://user-images.githubusercontent.com/32375741/64280598-d4a88980-cf27-11e9-95f9-f6f773cb5b65.png)

Si hago click en el primer botón "Ver" (el que se encuentra a la derecha de la columna de "Apellido y Nombre"), filtraría todas las asignaturas en las que está inscripto ese participante (buscando por el parámetro "participant_id" en la base de datos).
Aparece el siguiente error:

![image](https://user-images.githubusercontent.com/32375741/64280651-f30e8500-cf27-11e9-8832-c37e46ae81b4.png)

La parte del código en donde se encuentran estos dos botones es en /protected/layouts/views/incripciones/admin.php:

![image](https://user-images.githubusercontent.com/32375741/64280529-b2af0700-cf27-11e9-8f20-52781a03def1.png)

El conflicto se genera por el nuevo cambio que agregamos para obtener el año y mostrarlo en el título de la página:

$_GET["Incripciones"]["anio_academico"]

Esto funciona para la vista principal de Inscripciones, pero no para la url a la que nos redirecciona el botón "Ver", ya que tiene el parámetro "Incripciones", pero no el de "anio_academico", sino que tiene el de "participant_id" (en las línea 63 y 71 se define la "urlExpression" para cada botón)

**Comment by sergioviera** [comment]
Funciona, pero se genera issue #21
