### ISSUE TITLE
evaluar JD eSurvey

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/encuesta-docente#2]
https://www.jdsoft.com/jd-esurvey.html

**Comment by sergioviera** [comment]
- [ ] gratis
- [ ] codigo accesible
- [ ] crear usuarios para responder encuestas
- [ ] un usuario puede tener multiples encuestas

**Comment by nulmete** [comment]
Tuvimos problemas con la conexión y no encontramos mucha documentación como para consultar
