### ISSUE TITLE
Administración de Inscripciones

### ISSUE THREAD

**Issue by sergioviera** [UTN-FRD/encuesta-docente#3]
En la tabla de administración de inscripciones se debe cambiar los datos mostrados.
![image](https://user-images.githubusercontent.com/831628/44918976-adb2e880-ad12-11e8-93da-2d3c9c288d41.png)
Del alumno se debe mostrar el nombre y el legajo.
De la asignatura se debe mostrar el nombre, carrera y plan.
Año académico, ID y comentarios no es necesario mostrarlo.

**Comment by nulmete** [comment]
Query de prueba:

select p.firstname as alumno, a.descripcion as materia
from incripciones i
  inner join participants p
    on i.participant_id = p.participant_id
  inner join asignaturas a 
    on a.id = i.asignatura_id
